[package]
name = "noki_os"
version = "0.1.0"
edition = "2021"

[dependencies]
bootloader = "0.9.23"
spin = "0.5.2"
volatile = "0.2.6"

[dependencies.lazy_static]
version = "1.0"
features = ["spin_no_std"]

[[bin]]
name = "noki_os"
test = false
bench = false
